Add filetype when resolving path in case of loading into dataframe (#891)
# Description
## What is the current behavior?
<!-- Please describe the current behavior that you are modifying. -->
When a `.data` file is loaded into a pandas dataframe from a URL by
specifying file type, it fails. The file is basically a CSV format but
has the .data extension.

Example code
```
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  # URL for Iris data API

dataframe = aql.load_file(
            input_file=File(path=data_url, filetype=FileType.CSV)
        )
```

error log
```
ValueError: Unsupported filetype 'data' from file 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'.
```
<!--
Issues are required for both bug fixes and features.
Reference it using one of the following:

closes: #ISSUE
related: #ISSUE
-->
closes: #881


## What is the new behavior?
<!-- Please describe the behavior or changes that are being added by
this PR. -->

- Pass the filetype while resolving files for loading into data frame
- Add the corresponding test for this
-

## Does this introduce a breaking change?
No

### Checklist
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>