Tests: Fix error on retry
Our retry logic wasn't working because the `retry_if_exception_type` expected a tuple while we passed a list

Before:

```
============================================================================================== short test summary info ===============================================================================================
FAILED tests/test_example_dags.py::test_example_dag[calculate_popular_movies] - TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
====================================================================================== 1 failed, 1 passed, 4 warnings in 1.30s =======================================================================================

```

After:

```
============================================================================================== short test summary info ===============================================================================================
FAILED tests/test_example_dags.py::test_example_dag[calculate_popular_movies] - requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/astronomer/astro-sdk/main/tes...
====================================================================================== 1 failed, 1 passed, 4 warnings in 1.65s =======================================================================================

```