Add symlinked LICENSE to subprojects
Without this you get the following errors:

```
❯ nox -s build
nox > Running session build
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/build
nox > python -m pip install build
nox > python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core ~=3.2)
* Getting dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/Users/kaxilnaik/Documents/GitHub/astronomer/astro-sdk/python-sdk/.nox/build/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/Users/kaxilnaik/Documents/GitHub/astronomer/astro-sdk/python-sdk/.nox/build/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/kaxilnaik/Documents/GitHub/astronomer/astro-sdk/python-sdk/.nox/build/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/private/var/folders/7j/hsytyfm543100rv6xnr5vynr0000gn/T/build-env-atmsk2vw/lib/python3.10/site-packages/flit_core/buildapi.py", line 82, in build_sdist
    path = SdistBuilder.from_ini_path(pyproj_toml).build(Path(sdist_directory))
  File "/private/var/folders/7j/hsytyfm543100rv6xnr5vynr0000gn/T/build-env-atmsk2vw/lib/python3.10/site-packages/flit_core/sdist.py", line 178, in build
    ti = tf.gettarinfo(path, arcname=pjoin(self.dir_name, relpath))
  File "/Users/kaxilnaik/.pyenv/versions/3.10.4/lib/python3.10/tarfile.py", line 1855, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

ERROR Backend subprocess exited when trying to invoke build_sdist
nox > Command python -m build failed with exit code 1
nox > Session build failed.
```

(cherry picked from commit 3815904fa3a1b99223ac835c0169fddaae5830ff)