Fix failing test for 2.2.5 (#414)
There was a typo in the file to include for 2.2.5 testing

```
============================ no tests ran in 0.01s =============================
ERROR: file or directory not found: integration_test_dag.py

```



I don't think this file was run with Airflow 2.3 or otherwise too in our CI. One reason might be that it is because the filename does not start with test_