Fix data validation tests (#1613)
# Description
## What is the current behavior?
currently tests are failing in main with error 
```
FAILED tests_integration/sql/operators/data_validation/test_check_column.py::test_column_check_operator_with_table_dataset[snowflake] - AttributeError: module 'astro.sql' has no attribute 'ColumnCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_column.py::test_column_check_operator_with_table_dataset[bigquery] - AttributeError: module 'astro.sql' has no attribute 'ColumnCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_column.py::test_column_check_operator_with_table_dataset[postgresql] - AttributeError: module 'astro.sql' has no attribute 'ColumnCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_column.py::test_column_check_operator_with_table_dataset[sqlite] - AttributeError: module 'astro.sql' has no attribute 'ColumnCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_column.py::test_column_check_operator_with_table_dataset[redshift] - AttributeError: module 'astro.sql' has no attribute 'ColumnCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_table.py::test_column_check_operator_with_table_dataset[snowflake] - AttributeError: module 'astro.sql' has no attribute 'SQLCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_table.py::test_column_check_operator_with_table_dataset[bigquery] - AttributeError: module 'astro.sql' has no attribute 'SQLCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_table.py::test_column_check_operator_with_table_dataset[postgresql] - AttributeError: module 'astro.sql' has no attribute 'SQLCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_table.py::test_column_check_operator_with_table_dataset[sqlite] - AttributeError: module 'astro.sql' has no attribute 'SQLCheckOperator'
FAILED tests_integration/sql/operators/data_validation/test_check_table.py::test_column_check_operator_with_table_dataset[redshift] - AttributeError: module 'astro.sql' has no attribute 'SQLCheckOperator'
```


## What is the new behavior?
Fix import path

## Does this introduce a breaking change?


### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Daniel Imberman <daniel.imberman@gmail.com>