Fix error help for astro-cli (#1266)
# Description

## What is the current behavior?

Currently, when using an unknown flag in astro-cli, it raises (under the
condition that the flag is implemented in cobra but not in sql-cli):
> Try 'flow -h' for help.

In case the flag is not implemented in astro-cli cobra, we currently see
cobra error output
> Error: unknown flag: --foo

^this needs to be fixed on astro-cli cobra side.

## What is the new behavior?

Monkey-patch rich_format_error to make it environment aware. So that
when running in astro-cli it says:
> Try 'astro flow -h' for help.

## Does this introduce a breaking change?

No.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary