Tests: Make local runner compatible with Airflow <2.3 (#1022)
# Description
## What is the current behavior?
Without it, the tests for Airflow 2.2.5 gives the following error:

```python
>       if ti.map_index > 0:
E       AttributeError: 'TaskInstance' object has no attribute 'map_index
```


## What is the new behavior?
<!-- Please describe the behavior or changes that are being added by
this PR. -->

- Since `map_index` was added to Airflow 2.3, this PR makes it
compatible to both <2.3 and >= 2.3