Pin the sphinx version to 5.0.0 (#915)
build_docs is failing in main due to recent changes in sphinx. not sure what immediate I can do so pined the sphinx version to 5.0.0

sphinx: https://github.com/sphinx-doc/sphinx/pull/10852
```
Warning, treated as error:
Using the :property: flag with the py:method directiveis deprecated, use ".. py:property::" instead.
make: *** [Makefile:20: html] Error 2
nox > Command make html failed with exit code 2
nox > Session build_docs failed.
Error: Process completed with exit code 1.
0s
```

(cherry picked from commit a55f552819016df7bf217f3360fa746c7f3b8c32)