Fix benchmark permissions
When trying to run `make run_job`, it raised the following exceptions:

google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/astronomer-dag-authoring/jobs?prettyPrint=false: Access Denied: Project astronomer-dag-authoring: User does not have bigquery.jobs.create permission in project astronomer-dag-authoring.

Copying file:///tmp/results-2022-07-06T14:11:59.ndjson [Content-Type=application/octet-stream]...
AccessDeniedException: 403 astro-sdk-gke-benchmark@astronomer-dag-authoring.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object.

AccessDeniedException: 403 astro-sdk-gke-benchmark@astronomer-dag-authoring.iam.gserviceaccount.com does not have storage.objects.delete access to the Google Cloud Storage object.