Fix DistutilsOptionError (#571)
Fix: #570

Solve the CI currently happening in all our branches:
```
File "/home/runner/work/astro-sdk/astro-sdk/.nox/type_check-3-8/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 301, in _ensure_previously_set
          raise OptionError(msg)
      distutils.errors.DistutilsOptionError: No configuration found for dynamic 'description'.
      Some dynamic fields need to be specified via `tool.setuptools.dynamic`
      others must be specified via the equivalent attribute in `setup.py`.
      [end of output]
```

Co-authored-by: @uranusjr