Fix AWS ecs instance issue (#1973)
Fix the AWS ECS unknown instance issue by adding waiting time. 

```
[2023-06-07, 07:09:03 UTC] {logging_mixin.py:149} WARNING - TypeError: object of type 'NoneType' has no len()
[2023-06-07, 07:09:03 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/master_dag.py", line 124, in start_sftp_ftp_services_method
    while get_instances_status(instance_id) != "running":
  File "/usr/local/airflow/dags/master_dag.py", line 134, in get_instances_status
    response = client.describe_instances(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-034a0829d215c3db0' does not exist
```

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>